name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main, develop ]
jobs:
  Check-linter:
    name: "Java Linter Check"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Validate code format
        run: mvn spotless:check

  test:
    name: "Java Test"
    runs-on: ubuntu-latest

    steps:
      - name: Testing Code
        run: mvn test

  build:
    name: "Java Build"
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: mvn clean compile -DskipTests

      - name: Run linter (Checkstyle)
        run: mvn checkstyle:check

      - name: Verify Java version compatibility
        run: mvn compiler:testCompile "-Dmaven.compiler.release=21"
